### ISSUE TITLE
UnsupportedOperationException: Unable to open DISPLAY

### ISSUE THREAD

**Issue by dyskette** [flathub/io.conduktor.Conduktor#52]
Hi, I cannot run this on Fedora Silverblue 36. Help?

```
$ flatpak run io.conduktor.Conduktor 
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.controls specified to --add-opens
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Eonfge** [comment]
Can you tell me what window manager you use? I have to admit that I never tested this much on Wayland, so perhaps it doesn't actually work on Wayland.

**Comment by dyskette** [comment]
Yes, I'm using GNOME 42 Wayland

**Comment by Eonfge** [comment]
It appears that Java FX has no Wayland support.

Could you do two things for me?
- Reset your Flathub permissions to the default
-  Try the patch of this merge-request: https://github.com/flathub/io.conduktor.Conduktor/pull/53

If it then works for you, I'll publish the change
